import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const pretendard = localFont({
  src:'../fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={pretendard.className}
      >
        <Navbar />
        {children}

      </body>
    </html>
  );
}
